### PR TITLE
#1422 Textarea enable linebreak (submitOnEnter)

### LINKED ISSUE #1422: OcTextArea: Add a way to enter a line break
### Steps to reproduce
1. Type enter in OcTextArea
2. Change event is emitted and enter is swallowed

### Expected behaviour
There should be a way to enter a line break, maybe with ctrl+enter?

### Actual behaviour
There is no way to enter a line break ...

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

### PR DESCRIPTION
**Pull request by paulcod3**
## Description
See #1422 

## Related Issue

- Fixes #1422

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [x] Documentation added/updated

### CODE REVIEW

**Review by pascalwengerter — CHANGES_REQUESTED** [review]
Please add a changelog item in `changelog/unreleased/`, linking to the issue this is addressing (if applicable)

Also, please run `yarn lint:eslint --fix` to fix linter issues locally (they're failing in CI currently) ;)

**Comment by paulcod3** [comment]
@pascalwengerter yes sorry only wanted to create a WIP PR ^^ but ofc you are right I fixed it

**Comment by pascalwengerter** [comment]
> @pascalwengerter yes sorry only wanted to create a WIP PR ^^ but ofc you are right I fixed it

No worries, was under the impression it's ready to review since you requested it ;) good work, either way!

File: src/components/OcTextarea.vue [hunk 1]
```diff
@@ -102,6 +102,16 @@ export default {
       type: Boolean,
       default: false,
     },
+    /**
+     * Configure if the value should be emited on 'enter' or if it should do a linebreak
```
Comment (kulmann) [inline src/components/OcTextarea.vue:106]:
```suggestion
     * Configure if the value should be emitted on 'enter' or if it should do a linebreak
```

File: src/components/OcTextarea.vue [hunk 2]
```diff
@@ -102,6 +102,16 @@ export default {
...
+     * if true: 'enter' emits value, ctrl + enter creates linebreak
```
Comment (kulmann) [inline src/components/OcTextarea.vue:107]: Please also add `shift + enter`

File: src/components/OcTextarea.spec.js [hunk 3]
```diff
@@ -0,0 +1,133 @@
...
+        warningMessage: "You may pass.",
+        descriptionMessage: "Your should pass.",
+      })
+      const messageEl = wrapper.find(".oc-textarea-message span")
+      expect(messageEl.attributes().class).toBe(
+        "oc-textarea-description oc-textarea-warning oc-textarea-danger"
+      )
+      expect(messageEl.text()).toBe("You shall not pass.")
+    })
+    it("should give waring message priority over description message", () => {
```
Comment (kulmann) [inline src/components/OcTextarea.spec.js:100]:
```suggestion
    it("should give warning message priority over description message", () => {
```

File: src/components/OcTextarea.spec.js [hunk 4]
```diff
@@ -0,0 +1,133 @@
...
+    })
+  })
+  describe("change events", () => {
+    it("should emit an change event if submitOnEnter is true", async () => {
+      const wrapper = getShallowWrapper({ submitOnEnter: true })
+      expect(wrapper.emitted().change).toBeFalsy()
+      await wrapper.find("textarea").trigger("keydown.enter")
+      expect(wrapper.emitted().change).toBeTruthy()
+    })
+    it("shouldnt emit an change event if submitOnEnter is false", async () => {
```
Comment (kulmann) [inline src/components/OcTextarea.spec.js:126]:
```suggestion
    it("shouldn't emit a change event if submitOnEnter is false", async () => {
```

File: src/components/OcTextarea.spec.js [hunk 5]
```diff
@@ -0,0 +1,133 @@
...
+    it("should emit an input event on typing", async () => {
+      const wrapper = getShallowWrapper()
+      expect(wrapper.emitted().input).toBeFalsy()
+      await wrapper.find("textarea").setValue("a")
+      expect(wrapper.emitted().input).toBeTruthy()
+      expect(wrapper.emitted().input[0][0]).toBe("a")
+    })
+  })
+  describe("change events", () => {
+    it("should emit an change event if submitOnEnter is true", async () => {
```
Comment (kulmann) [inline src/components/OcTextarea.spec.js:120]:
```suggestion
    it("should emit a change event if submitOnEnter is true", async () => {
```

File: src/components/OcTextarea.vue [hunk 6]
```diff
@@ -158,9 +168,10 @@ export default {
       this.$emit("focus", value)
     },
     onKeyDown(e) {
-      if (e.keyCode === 13) {
+      if (this.submitOnEnter && e.keyCode === 13 && !e.ctrlKey && !e.shiftKey) {
```
Comment (kulmann) [inline src/components/OcTextarea.vue:171]:
```suggestion
      if (this.submitOnEnter && e.enterKey && !e.ctrlKey && !e.shiftKey) {
```
I like that you're using named keys. Please also change the `keyCode === 13` to the named enterKey then for consistency.

Comment (paulcod3) [reply src/components/OcTextarea.vue:171]: sadly keyenter doesn't exist on the event, but I created a mini workaround to make it more readable

**Comment by paulcod3** [comment]
All issues mentioned should be resolved

File: src/components/OcTextarea.vue [hunk 7]
```diff
@@ -158,9 +168,11 @@ export default {
       this.$emit("focus", value)
     },
     onKeyDown(e) {
-      if (e.keyCode === 13) {
+      e.keyEnter = e.key === "Enter";
```
Comment (kulmann) [inline src/components/OcTextarea.vue:171]: Hm.... personally in favor of not altering the event. Since `enterKey` doesn't exist, you could just create a `const` and use it in the `if` statement, that still improves the readability a bit.
I.e. like this:
```js
const enterKey = e.key === "Enter"
if (this.submitOnEnter && enterKey && !e.ctrlKey && !e.shiftKey) {
```

Comment (paulcod3) [reply src/components/OcTextarea.vue:171]: looks fine for me ^^

**Review by kulmann — APPROVED** [review]
LGTM 👍

**Review by pascalwengerter — APPROVED** [review]
Would be superb to have working examples of both configs, but changes in general LGTM and props for adding tests! 💪🏽
